version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "09:30"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  reviewers:
  - liuliu-dev
  labels:
  - dependencies
