name: Run CI on commit-graph
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn lint
      - name: Type check
        run: yarn compile
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
